version: "3.8"
name: asp_net_msssql
services:
    asp_restful_web_api:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "49900:80"
        depends_on:
          - mssqldb

    mssqldb:
        build:
          context: .
          dockerfile: Dockerfile_mssql
        ports:
          - "1433:1433"