# use MSSQL 2022 image
FROM mcr.microsoft.com/mssql/server:2022-latest

# create directory within SQL container for database files
RUN mkdir -p /opt/mssql-scripts

# copy the database files from host to container
COPY sql_add_mssql.sql /opt/mssql-scripts

# set environment variables
ENV MSSQL_SA_PASSWORD=!Aa112233
ENV ACCEPT_EULA=Y

# run initial scripts
RUN /opt/mssql/bin/sqlservr --accept-eula & sleep 10 \
    && /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P '!Aa112233' -i /opt/mssql-scripts/sql_add_mssql.sql \
    && pkill sqlservr